import mongoose from 'mongoose';

/**
 * One press of the SOS button that got as far as the server.
 *
 * It exists so an emergency is a record someone can open, acknowledge and
 * close — not only an email that may or may not have arrived. The patient's
 * exact location lives here, behind authenticated access, and never in a
 * push payload or notification body.
 *
 * Who may read it is decided at read time from Hospital.ownerId, not from a
 * list stored here, so a facility that changes hands does not leave the
 * previous owner with access.
 */
export const EMERGENCY_STATUSES = ['open', 'acknowledged', 'resolved', 'no_facility'];
export const ACTIVE_EMERGENCY_STATUSES = ['open', 'acknowledged'];

const facilitySchema = new mongoose.Schema({
    hospitalId: { type: mongoose.Schema.Types.ObjectId, ref: 'Hospital', required: true },
    // Snapshotted so the patient's view of "who was alerted" stays true even
    // if the facility later edits its profile.
    name: { type: String, required: true },
    phone: { type: String, default: '' },
    distanceKm: { type: Number, required: true },
    /** At least one channel was accepted for delivery: push service or email provider. */
    reached: { type: Boolean, default: false }
}, { _id: false });

const emergencyAlertSchema = new mongoose.Schema({
    patientId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },

    /**
     * Generated by the client per SOS attempt and reused on retry, so a
     * request that timed out on a bad connection and is sent again becomes
     * the same alert rather than a second one.
     */
    clientRequestId: { type: String, default: null },

    location: {
        type: { type: String, enum: ['Point'], default: 'Point' },
        coordinates: { type: [Number], required: true } // [longitude, latitude]
    },
    accuracyMetres: { type: Number, default: null },

    status: { type: String, enum: EMERGENCY_STATUSES, default: 'open' },
    facilities: { type: [facilitySchema], default: [] },

    delivery: {
        inAppCreated: { type: Number, default: 0 },
        pushDevicesAccepted: { type: Number, default: 0 },
        pushFailed: { type: Number, default: 0 },
        emailsAccepted: { type: Number, default: 0 },
        /** True only when a push service or email provider accepted a message. */
        confirmed: { type: Boolean, default: false }
    },

    acknowledgedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
    acknowledgedAt: { type: Date, default: null },
    resolvedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
    resolvedAt: { type: Date, default: null }
}, { timestamps: true });

emergencyAlertSchema.index(
    { patientId: 1, clientRequestId: 1 },
    { unique: true, partialFilterExpression: { clientRequestId: { $type: 'string' } } }
);
emergencyAlertSchema.index({ patientId: 1, createdAt: -1 });
emergencyAlertSchema.index({ 'facilities.hospitalId': 1, createdAt: -1 });

export default mongoose.model('EmergencyAlert', emergencyAlertSchema);
